openapi: "3.0.0"
info:
  title: "Intranet Bookshelf API"
  description: "REST API communication between the front-end (React) and the back-end (NodeJS)."
  contact:
    name: "J. Trpka"
    url: "https://www.github.com/jtrpka0912"
    email: "jtrpka0912@gmail.com"
  version: "1.0.0"
servers:
  - url: "http://localhost:3001/api/v1"
    description: "Development Server"
components:
  examples:
    Book:
      summary: eBook Book Example
      description: A simple example of an ebook Book example.
      value:
        id: 4
        type: book
        name: Journey to the West
        path: /path/to/ebook/journey-to-the-west.pdf
        cover: /path/to/images/cover/journey-to-the-west.jpg
        didRead: false
        author: Unknown
    Error:
      summary: Error example
      description: A simple error example of the 404 errors.
      value:
        errorCode: 404
        errorCodeMessage: Not Found.
        errorMessage: Object was not found.
    File:
      summary: eBook Example
      description: A simple example of an ebook example.
      value:
        id: 1
        type: comicbook
        name: The Boys
        path: /path/to/ebook/the-boys/issues/001.cbz
        cover: /path/to/images/cover/the-boys/issues/001.cbz
        didRead: false
    Magazine:
      summary: eBook Magazine Example
      description: A simple example of an ebook Magazine example.
      value:
        id: 19
        type: magazine
        name: Magpi
        path: /path/to/magazines/magpi/issue014.pdf
        cover: /path/to/images/cover/magpi-issue014.jpg
        didRead: false
        issue: 14
    Shelf:
      summary: Bookshelf Example
      description: An example of a simple bookshelf.
      value:
        id: 2
        name: Bookshelf of Books
        root: /path/to/root
        showDirectories: true
        multiFile: false
  parameters:
    ShelfID:
      name: shelfId
      in: path
      description: Primary key for a shelf.
      required: true
      schema:
        type: integer
        minimum: 1
      example:
        value: 3
      style: simple
  requestBodies:
    CreateShelf:
      description: The fields needed to create a bookshelf.
      required: true
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/Shelf'
          example:
            $ref: '#/components/examples/Shelf'
    UpdateShelf:
      description: The fields to update a bookshelf.
      required: true
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/Shelf'
          example:
            $ref: '#/components/schemas/Shelf'
  responses:
    '400':
      description: 400 Error - Bad Request
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/Error'
    '404':
      description: 404 Error - Not Found
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Book:
      allOf:
      - $ref: '#/components/schemas/File'
      - description: Data representing an ebook Book inside the bookshelf.
      - type: object
        example: 
          $ref: '#/components/examples/Book'
        properties:
          author:
            type: string
            description: The author of the ebook book.
    Error:
      type: object
      description: Base error object for other errors.
      example:
        $ref: '#/components/examples/Error'
      properties:
        errorCode:
          type: integer
          description: The error code number
        errorCodeMessage:
          type: string
          description: The error code message.
        errorMessage:
          type: string
          description: Message explaining the cause of the error.
      required:
        - errorCode
        - errorCodeMessage
      readOnly: true
    File:
      type: object
      description: Data representing an ebook inside the bookshelf.
      example:
        $ref: '#/components/examples/File'
      properties:
        id:
          type: integer
          description: The primary key.
          minimum: 1
        type:
          type: string
          description: Is this a book, magazine, or comic book?
          enum:
          - book
          - magazine
          - comicbook
        name:
          type: string
          description: Name of the ebook.
        path:
          type: string
          description: Path to the ebook in the NAS.
        cover:
          type: string
          description: Path to the image, created in backend, of the ebook.
        didRead:
          type: boolean
          description: Did the user read the ebook.
      required:
        - id
        - type
        - name
        - path
    Files:
      type: array
      description: An array of ebook files.
      items:
        $ref: '#/components/schemas/File'
    Folder:
      type: object
      description: Data representing a directory inside the bookshelf.
      properties:
        id:
          type: integer
          description: The primary key.
          minimum: 1
        name:
          type: string
          description: Name of the directory; for example, a publisher or genre name.
        path:
          type: string
          description: Path to the directory in the NAS.
      required:
        - id
        - name
        - path
    Folders:
      type: array
      description: An array of directories.
      items:
        $ref: '#/components/schemas/Folder'
    Magazine:
      allOf:
        - $ref: '#/components/schemas/File'
        - description: Data representing an ebook Magazine inside the bookshelf.
        - type: object
          example: 
            $ref: '#/components/examples/Book'
          properties:
            issue:
              type: integer
              description: The issue number of the ebook magazine.
    Shelf:
      type: object
      description: A single collection of ebooks from a root directory.
      example:
        $ref: '#/components/examples/Shelf'
      properties:
        id:
          type: integer
          description: The primary key.
          minimum: 1
        name:
          type: string
          description: Name of the shelf or collection.
        root:
          type: string
          description: The starting path of the collection.
        showDirectories:
          type: boolean
          description: Allow the explorer to show all files (false) at once or separated in their respective directories (true).
          default: true
        multiFile:
          type: boolean
          description: Allow a single ebook to be a directory with multiple file types inside.
          default: false
      required:
        - id
        - name
        - root
    Shelves:
      type: array
      description: An array of collections of ebooks.
      items:
        $ref: '#/components/schemas/Shelf'
paths:
  /shelves:
    summary: Shelves Endpoints
    description: An endpoint to interact with multiple shelves or create a new shelf.
    get:
      tags: 
      - read
      - shelf
      summary: Retrieve all bookshelves.
      description: Retrieve all bookshelves that will allow the user to select and navigate.
      operationId: retrieve-shelves
      responses:
        '200':
          description: Retrieved a list of bookshelves.
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Shelves'
    post:
      tags:
      - shelf
      - create
      summary: Create a bookshelf.
      description: Create a single bookshelf that will serve as a collection of ebooks.
      operationId: create-shelf
      requestBody:
       $ref: '#/components/requestBodies/CreateShelf'
      responses:
        '200':
          description: Created a new bookshelf.
          content:
            'application/json': {}
        '400':
          $ref: '#/components/responses/400'
  /shelves/{shelfId}:
    summary: Single Shelf Endpoints
    description: An endpoint to interact with a single shelve.
    parameters:
      - $ref: '#/components/parameters/ShelfID'
    get:
      tags:
      - read
      - shelf
      summary: Retrieve single bookshelf.
      description: Retrieve a single bookshelf that will retrieve the rules for the collection of ebooks.
      operationId: retrieve-shelf
      responses:
        '200':
          description: Retrieved a single bookshelf.
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Shelf'
        '404':
          $ref: '#/components/responses/404'
    put:
      tags:
      - shelf
      - update
      summary: Edit single bookshelf.
      description: Edit a single bookshelf by changing its name and rules.
      operationId: edit-shelf
      requestBody:
        $ref: '#/components/requestBodies/UpdateShelf'
      responses:
        '200':
          description: Edited an existing bookshelf.
          content:
            'application/json': {}
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
    delete:
      tags:
      - delete
      - shelf
      summary: Remove single bookshelf.
      description: Remove a single bookshelf.
      operationId: remove-shelf
      responses:
        '200':
          description: Removed a single bookshelf.
          content:
            'application/json': {}
        '404':
          $ref: '#/components/responses/404'
tags:
- name: create
  description: Create operations
- name: delete
  description: Delete operations
- name: ebook
  description: eBook operations
- name: read
  description: Read operations
- name: shelf
  description: Bookshelf operations
- name: update
  description: Update operations
